using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace WebApii_Abp.Books
{
    public class Book : BookBase
    {
        //<suite-custom-code-autogenerated>
        protected Book()
        {

        }

        public Book(Guid id, int bookId, double price, string? bookName = null)
            : base(id, bookId, price, bookName)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}