using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace WebApii_Abp.Books
{
    public class BookManager : BookManagerBase
    {
        //<suite-custom-code-autogenerated>
        public BookManager(IBookRepository bookRepository)
            : base(bookRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}